name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      # Download repository source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Scan repository for secrets
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2

      # Static Application Security Testing
      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t flask-demo .

      # Scan Docker image for vulnerabilities
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: flask-demo
          format: table
          exit-code: 0
